### ISSUE TITLE
Consider to instantiate ipfsClient with options

### ISSUE THREAD

**Issue by xmaysonnave** [ipfs-shipyard/ipfs-provider#20]
[enhancement]

The http-client.js instantiate ipfsClient in the maybeApi method with a single parameter.
This parameter could be according to the documentation in the following form:
https://github.com/ipfs/js-ipfs-http-client#importing-the-module-and-usage

```
// connect to ipfs daemon API server
const ipfs = ipfsClient('http://localhost:5001') // (the default in Node.js)
// or connect with multiaddr
const ipfs = ipfsClient('/ip4/127.0.0.1/tcp/5001')
```

However if ipfs-provider users want to tune a global timeout to all request the options mode should be used, https://github.com/ipfs/js-ipfs-http-client#global-timeouts.

```
// or using options
const ipfs = ipfsClient({ host: 'localhost', port: '5001', protocol: 'http, timeout: '2m'' })
// or specifying a specific API path
const ipfs = ipfsClient({ host: '1.1.1.1', port: '80', apiPath: '/ipfs/api/v0', timeout: '2m' })
```

I'm particularly interrested with the global timeout option.

Thanks

**Comment by lidel** [comment]
@xmaysonnave sounds like a good proposal.
Would you have bandwidth to submit a PR?

**Comment by xmaysonnave** [comment]
@lidel It could be. I need to deliver first as the lockdown here in India troubled my schedule.
However in the meantime it could be nice to prepare what will be implemented.
As far as I can see here are the options I found from the doc.
https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-http-client#api

1 - the connect to ipfs daemon API server is the current implementation
const ipfs = ipfsClient('http://localhost:5001')

2 - the connect with multiaddr
const ipfs = ipfsClient('/ip4/127.0.0.1/tcp/5001')
Not implemented yet but not needed right now from my side.
I suggest to postpone it ?

3 - the connect using options
**Standard**
const ipfs = ipfsClient({ host: 'localhost', port: '5001', protocol: 'http' })
const ipfs = ipfsClient({ host: '1.1.1.1', port: '80', apiPath: '/ipfs/api/v0' })
**Custom Header:**
const ipfs = ipfsClient({
  host: 'localhost',
  port: 5001,
  protocol: 'http',
  headers: {
    authorization: 'Bearer ' + TOKEN
  }
})
**Global Timeouts**
const ipfs = ipfsClient({ timeout: 10000 })

The using options should cover this scope:
- host
- port
- protocol
- headers
- timeout

4 - What about the tests ??

5 - What is the default timeout default value, unable to find that ?

6 - is there any missing options ?

Let me know

**Comment by xmaysonnave** [comment]
I seem to be totally wrong here:
https://github.com/ipfs-shipyard/ipfs-provider#httpclient
According to your documentation, configuration object supported by the constructor is supported.
Multiaddr is also already supported.
Am I missing something ?

**Comment by xmaysonnave** [comment]
I successfully use the configuration object :

```
      const { ipfs, provider } = await getIpfs({
        providers: [
          httpClient({
            apiAddress: {
              protocol: protocol,
              host: apiUrl.hostname,
              port: port,
              timeout: '2m'
            }
          })
        ]
      })
```
This feature request seems irrelevant. Feel free to close it.
Thanks

**Comment by lidel** [comment]
@xmaysonnave apologies for missing this! Glad you figured it out.
Question: did you miss example at https://github.com/ipfs-shipyard/ipfs-provider#httpclient or was it unclear? Any way we can improve README and examples there?
