### ISSUE TITLE
Customize the fallback order of IPFS providers

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/ipfs-provider#3]
There should be a way to customize the order in which providers are tried.
For example, if I want to ensure my app tries remote API before falling back to window.ipfs and embedded js-ipfs, I should be able to specify providers via ordered list:

```js
const { ipfs, provider } = await getIpfs({
  fallbackOrder: ['api','window.ipfs', 'js-ipfs']  // strings? import enums?
  apiAddress:    '/ip4/10.1.1.1/tcp/5002'
  jsIpfsOpts:    {}
})
```

Additional notes:
- Providing ordered list of providers should take precedence over individual flags such as `tryApi: false`
- cc @parkan for thoughts and suggestions for use cases at Internet Archive

**Comment by parkan** [comment]
hi, sorry this slipped past me back in June

thoughts:
- having multiple control mechanisms for whether providers should be tried and in what order is difficult to reason about (would need to read docs to understand inclusion in fallbackOrder takes precedence over tryThing, for ex.)

using fallbackOrder alone (with a healthy default) is sufficient to signify both, though (1) you need a way to enumerate legal values to know what to put in there (2) any new providers added in an update would not be enabled if you have a custom fallbackOrder set (though maybe that’s for the best)
- another way could be to use a `Map` that signifies order (key order) and enabled/disabled state (bool values), though of course we still don’t have a nice looking Map literal syntax 😢 
- re: IA, it’s probably best to sync up with Mitra as to their current thinking

**Comment by lidel** [comment]
Idea:   `providers` – a predefined Map of Symbols:

```js
import { getIpfs, providers } from 'ipfs-provider'
const { httpClient, windowIpfs, jsIpfs } = providers
const { ipfs, provider } = await getIpfs({
  fallbackOrder: [ httpClient, windowIpfs, jsIpfs ]
  apiAddress:    '/ip4/10.1.1.1/tcp/5002'
  jsIpfsOpts:    {}
})
```

**Comment by parkan** [comment]
what are the value in this example?

**Comment by lidel** [comment]
I was thinking along these lines:
```js
const providers = Object.freeze({ 
  httpClient: Symbol('httpClient')
  windowIpfs: Symbol('windowIpfs')
  jsIpfs: Symbol('jsIpfs')
})
```

cc @hugomrdias if there is a better way

**Comment by hugomrdias** [comment]
```js
// providers.js

export {
	httpClient : (options = {}) => { 
		options = mergeOptions(defaults, options)
		return 'everything needed'
	},
	windowIpfs : (options = {}) => { 
		options = mergeOptions(defaults, options)
		return 'everything needed'
	},
	jsIpfs : (options = {}) => { 
		options = mergeOptions(defaults, options)
		return 'everything needed'
	},
}
```

```js
import { getIpfs, providers } from 'ipfs-provider'
const { httpClient, windowIpfs, jsIpfs } = providers
const { ipfs, provider } = await getIpfs([ 
	httpClient({apiAddress: '/ip4/10.1.1.1/tcp/5002'}), 
	windowIpfs(), 
	jsIpfs({})
])
```

i would do it like this

**Comment by lidel** [comment]
Below should address:
- [x] lazy constructors
- [x] support global options

```js
// providers.js

export {
	httpClient : (options = {}) => { 
		options = mergeOptions(defaults, options)
		return () => 'everything needed'
	},
	windowIpfs : (options = {}) => { 
		options = mergeOptions(defaults, options)
		return () => 'everything needed'
	},
	jsIpfs : (options = {}) => { 
		options = mergeOptions(defaults, options)
		return () => 'everything needed'
	},
}
```

```js
// sample use

import { getIpfs, providers } from 'ipfs-provider'
const { httpClient, windowIpfs, jsIpfs } = providers
const { ipfs, provider } = await getIpfs({
	providers: [ 
		httpClient({ apiAddress: '/ip4/10.1.1.1/tcp/5002' }), 
		windowIpfs({ commands: ['add','cat'] }), 
		jsIpfs({
			getJsIpfs: () => import('ipfs'),
			jsIpfsOpts: { /* advanced config */ }
		})
	],
    someGlobalOption: 'some value'
})
```

Y/n? Anything missing?

**Comment by parkan** [comment]
lgtm!
